### ISSUE TITLE
Pandas 0.20.3 breaks disaggregation

### ISSUE THREAD

**Issue by arbennett** [UW-Hydro/MetSim#109]
This is the error that gets raised:
```
Traceback (most recent call last):
  File "./scripts/ms", line 113, in <module>
    main()
  File "./scripts/ms", line 109, in main
    ms.run()
  File "/home/bzq/research/metsim-dev/MetSim/metsim/metsim.py", line 326, in run
    self.state.sel(**locs), self.disagg, times, label)
  File "/home/bzq/research/metsim-dev/MetSim/metsim/metsim.py", line 643, in wrap_run
    df_base = func(df, params, sg, elev=elev, swe=swe)
  File "/home/bzq/research/metsim-dev/MetSim/metsim/methods/mtclim.py", line 56, in run
    calc_srad_hum(forcing, sg, elev, params)
  File "/home/bzq/research/metsim-dev/MetSim/metsim/methods/mtclim.py", line 132, in calc_srad_hum
    yday = df.index.dayofyear - 1
AttributeError: 'MultiIndex' object has no attribute 'dayofyear'
```

**Comment by arbennett** [comment]
This is no longer possible after #120
